In [20]:
import pandas as pd
import requests
import numpy as np
from requests import get
from bs4 import BeautifulSoup as bs
from instaloader import Instaloader, Profile
from datetime import datetime, timedelta
from itertools import dropwhile, takewhile
from itertools import islice
import sqlite3

In [2]:


def most(name):
    L = Instaloader()
    SINCE = datetime.now()
    UNTIL = datetime.now()- timedelta(days = 30)
    posts =Profile.from_username(L.context, name).get_posts()
    
    temp=[]
    #for post in posts:
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        temp.extend(post.caption_hashtags)
    if not temp:
        p=[None,None,None,None,None]
    else:
        import collections
        counter=collections.Counter(temp)
        tags=pd.DataFrame()
        for x in range(len(counter.most_common(5))):
            test=pd.DataFrame([counter.most_common(5)[:][x]])
            tags=tags.append(test)
       
        p= list(tags.loc[:,0])
        if len(p) !=5:
            for x in range(len(p),5):
                p.insert(x, None)
    
    posts =Profile.from_username(L.context, name).get_posts()
    q=[]
    qwe=[]
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        qwe.append(post)
    posts_sorted_by_likes = sorted(qwe, key = lambda p: p.likes + p.comments,reverse=True)
    if not posts_sorted_by_likes:
        q=['no post within 30 days']
    else:
        for post in islice(posts_sorted_by_likes, 0, 1):
            q=[post.caption]
    return p,q

ig_n = pd.read_csv("player_ig2.csv")

count =0
L = Instaloader()
ig_most=pd.DataFrame()

for x in range(len(ig_n)):
    try:
        profile = Profile.from_username(L.context, ig_n.iat[x,2])
        a=most(ig_n.iat[x,2])
        tt = pd.DataFrame(np.column_stack([profile.userid,a[0][0],a[0][1],a[0][2],a[0][3],a[0][4],a[1]]))
        ig_most=ig_most.append(tt)
        count=count+1
    except:
        print(ig_n.iat[x,2])

ig_most.columns = ['Userid','tag1','tag2','tag3','tag4','tag5','Most_popular_post']
ig_most.index = range(0,len(ig_most))
print(count)

itsaverybradley
187

In [3]:
ig_most.head(5)

,Userid,tag1,tag2,tag3,tag4,tag5,Most_popular_post
0,10733526,risetogether,realworks,ad,None,None,My favorite time of year: playoff season! Runn...
1,1923491235,marchmadness,bingo,family,nextgeneration,finalfour,It’s almost that time....I’m not looking at du...
2,300139600,beststeakhousehandsdown,trutoatl,None,None,None,End of Chapter 6
3,375417881,historic,5thmaster,goat,None,None,Too many ppl don’t understand but Notre Dame i...
4,8174195,str8up,farouqisonfire,riprip,None,None,#farouqisonfire🔥🔥🔥 #str8up #riprip

In [14]:
ig_most.head(5)
ig_most.to_csv('ig_most.csv',index=False)

In [56]:
#========================================================================================

In [57]:
#get_comments()

def post(name):
    L = Instaloader()
    posts =Profile.from_username(L.context, name).get_posts()
    temp=pd.DataFrame()
    SINCE = datetime.now()
    UNTIL = datetime.now()- timedelta(days = 1)

    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        tt = [post.date,post.caption,post.likes,post.comments]
        temp=temp.append(tt)
    return temp

ig_n = pd.read_csv("player_ig3.csv")
L = Instaloader()
ig_profile=pd.DataFrame()
ig_post=pd.DataFrame()

for x in range(len(ig_n)):
    try:
        profile = Profile.from_username(L.context, ig_n.iat[x,2])
        tt = pd.DataFrame(np.column_stack([ig_n.iat[x,0],
                                           profile.full_name,profile.username, profile.userid,
                                           profile.biography,profile.external_url,profile.mediacount,
                                           profile.followers,profile.followees]))
        ig_profile=ig_profile.append(tt)

        a=post(ig_n.iat[x,2])
        for y in range(0,len(a),4):
            zz=pd.DataFrame(np.column_stack([profile.userid,a.iat[y,0],a.iat[y+1,0],a.iat[y+2,0],a.iat[y+3,0],a.iat[y+4,0]]))
            ig_post=ig_post.append(zz) 
    except:
        print(x)

#ig_post.insert(0, 'ig_post', range(1,len(ig_post)+1))
#ig_post.columns =['Postid','Userid','Time','Caption','Likes','Comments']
#ig_post.index = range(0,len(ig_post))
#ig_post['Time']= ig_post['Time'].astype('str')

#ig_profile.columns = ['Player_id','Fullname','Username','Userid','Bio','Url','Posts','Followers','Following']
#ig_profile.index = range(0,len(ig_profile))

2
4
6

In [58]:
ig_post

,0,1,2,3,4,5
0,300139600,2019-04-24 07:16:26,None,1058,14,<generator object Post.get_comments at 0x11c6e...
0,8174195,2019-04-24 06:12:26,#farouqisonfire🔥🔥🔥 #str8up #riprip,10707,131,<generator object Post.get_comments at 0x11c9c...
0,24949656,2019-04-24 00:15:41,I wanna thank the entire organization for anot...,18202,424,<generator object Post.get_comments at 0x11c9c...

In [59]:
ig_profile

,0,1,2,3,4,5,6,7,8
0,2,Al Horford,alhorford,10733526,,https://www.youtube.com/watch?v=YiZUWssMzyg&fe...,325,510869,267
0,4,Alan Anderson,dubblea74,1923491235,Proud Father✊🏾\n👨🏾‍🎓Michigan State Alumni\n Hu...,https://thecombinelasvegas.com/,80,5390,43
0,5,Alex Len,alexlen_21,300139600,"Ukraine ✈️Maryland ✈️Phoenix ✈️Atlanta ""A mo...",None,160,40800,1046
0,6,Alexis Ajinça,ajincaalexis,375417881,Frenchie 🇫🇷 🇬🇵9 years Center in the #NBA | Mar...,http://deluxmag.com/alexis-ajinca/,336,27337,510
0,7,Al-Farouq Aminu,chiefhasarrived,8174195,You may not control all the events that happen...,http://aminugoodworks.org/,485,77596,213
0,8,,iamamirjohnson,37867524,,None,549,200691,996
0,9,Andre Drummond,andredrummondd,24949656,TAGOD ™\nJamal Booker ® \n👻Andredrummondd\nKee...,http://bit.ly/2INkHyR,297,1116813,385
0,10,Andre Iguodala,andre,6246343,🔺,https://www.amazon.com/Sixth-Man-Memoir-Andre-...,29,1738972,118

In [118]:
temp

                                                   0
0                                2019-04-20 02:28:11
1  Big Game 3 win!! Huge night from @pskills43 to...
2                                              76817
3                                                468
4  <generator object Post.get_comments at 0x11c64...

In [126]:
L = Instaloader()
profile = Profile.from_username(L.context, "jlin7")

L = Instaloader()
posts =Profile.from_username(L.context, "jlin7").get_posts()

In [164]:
L = Instaloader()
posts =Profile.from_username(L.context, "jlin7").get_posts()

SINCE = datetime.now()
UNTIL = datetime.now()- timedelta(days = 20)



#for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
#    print(post, post.date, post.get_comments())

<Post Bwdej14lVUA> 2019-04-20 02:28:11 <generator object Post.get_comments at 0x11c56ee58>
<Post BwK1Z45FIam> 2019-04-12 20:44:17 <generator object Post.get_comments at 0x11c56ee58>
<Post BwDvUTyDBUN> 2019-04-10 02:34:21 <generator object Post.get_comments at 0x11c56ee58>

In [60]:

import instaloader
L = instaloader.Instaloader()
posts =instaloader.Profile.from_username(L.context, "jlin7").get_comment()
temp=pd.DataFrame()
SINCE = datetime.now()
UNTIL = datetime.now()- timedelta(days = 10)
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    tt = [post.date,post.caption,post.likes,post.comments,post.get_comments()]
    temp=temp.append(tt)

AttributeError: 'Profile' object has no attribute 'get_comment'

In [2]:
L = Instaloader()
profile = Profile.from_username(L.context, "jlin7") 
SINCE = datetime.now()
UNTIL = datetime.now()- timedelta(days = 10)
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, profile.get_posts())):
    a=post
k=set(a.get_comments())
list(k)[1][2]

'豪哥快拿個冠軍回台灣吃鹽酥雞和剉冰了啦'

In [62]:
import instaloader
L = instaloader.Instaloader()
profile = instaloader.Profile.from_username(L.context, "jlin7") 
SINCE = datetime.now()
UNTIL = datetime.now()- timedelta(days = 10)
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, profile.get_posts())):
    a=post
k=set(a.get_comments())
list(k)[1][2]

'@davis67389 urgh. Sorry to America that I mentioned earlier. I’m so glad you’re not American but you as an Asian, you shoulda support Lin. He’s not young but he can still make a huge impact to the game. He’s just different. If he’s trash, what you’re calling other players who can’t make to the NBA. Conclusion, he still play well in Toronto and worth more minutes.'

In [47]:
a

In [48]:
k=set(a.get_comments())

In [55]:
list(k)[1][2]

'@davis67389 urgh. Sorry to America that I mentioned earlier. I’m so glad you’re not American but you as an Asian, you shoulda support Lin. He’s not young but he can still make a huge impact to the game. He’s just different. If he’s trash, what you’re calling other players who can’t make to the NBA. Conclusion, he still play well in Toronto and worth more minutes.'

In [37]:
L = Instaloader()
profile = Profile.from_username(L.context, "jlin7") 
SINCE = datetime.now()
UNTIL = datetime.now()- timedelta(days = 10)

temp1=pd.DataFrame()
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, profile.get_posts())):
    a=post
    temp1=temp1.append(tt)
    return temp,list(k)[1][2]

In [1]:
##================done===================

In [1]:
import pandas as pd
import requests
import numpy as np
from requests import get
from bs4 import BeautifulSoup as bs
from instaloader import Instaloader, Profile
from datetime import datetime, timedelta
from itertools import dropwhile, takewhile
from itertools import islice
import sqlite3

In [2]:
ig_n = pd.read_csv("player_ig2.csv")

In [7]:
ig_n[:94]
len(ig_n[:94])
ig_n[94:]

94

In [7]:
def post(name):
    L = Instaloader()
    posts =Profile.from_username(L.context, name).get_posts()
    temp=pd.DataFrame()
    SINCE = datetime.now()
    UNTIL = datetime.now()- timedelta(days = 1)

    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        k=set(post.get_comments())
        tt = [post.date,post.caption,post.likes,post.comments,list(k)[1][2]]
        temp=temp.append(tt)
    return temp

ig_n = pd.read_csv("player_ig2.csv")
L = Instaloader()
ig_profile=pd.DataFrame()
ig_post=pd.DataFrame()

for x in range(len(ig_n)):
    try:
        #profile = Profile.from_username(L.context, ig_n.iat[x,2])
        #tt = pd.DataFrame(np.column_stack([ig_n.iat[x,0],
        #                                   profile.full_name,profile.username, profile.userid,
        #                                   profile.biography,profile.external_url,profile.mediacount,
        #                                   profile.followers,profile.followees]))
        #ig_profile=ig_profile.append(tt)
        
        a=post(ig_n.iat[x,2])
        for y in range(0,len(a),5):
            zz=pd.DataFrame(np.column_stack([profile.userid,a.iat[y,0],a.iat[y+1,0],a.iat[y+2,0],a.iat[y+3,0],a.iat[y+4,0]]))
            ig_post=ig_post.append(zz) 
    except:
        print(x)

ig_post.insert(0, 'ig_post', range(1,len(ig_post)+1))
ig_post.columns =['Postid','Userid','Time','Caption','Likes','Comments','Comment']
ig_post.index = range(0,len(ig_post))
ig_post['Time']= ig_post['Time'].astype('str')

15

JSON Query to graphql/query: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]

In [3]:
import pandas as pd
import requests
import numpy as np
from requests import get
from bs4 import BeautifulSoup as bs
from instaloader import Instaloader, Profile
from datetime import datetime, timedelta
from itertools import dropwhile, takewhile
from itertools import islice
import sqlite3

In [4]:
def post(name):
    L = Instaloader()
    posts =Profile.from_username(L.context, name)
    #profile = Profile.from_username(L.context, ig_n.iat[x,2])
    temp=pd.DataFrame()
    #temp1=pd.DataFrame()
    SINCE = datetime.now()
    UNTIL = datetime.now()- timedelta(days = 1)

    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts.get_posts())):
        k=set(post.get_comments())
        
        tt = [posts.userid,post.date,post.caption,post.likes,post.comments,list(k)[1][2]]
        
        temp=temp.append(tt)

    return temp

In [5]:

ig_n = pd.read_csv("player_ig2.csv")
L = Instaloader()
ig_profile=pd.DataFrame()
ig_post=pd.DataFrame()
z=0

for x in range(len(ig_n)):
    try:

        a=post(ig_n.iat[x,2])
        for y in range(0,len(a),6):
            zz=pd.DataFrame(np.column_stack([a.iat[y,0],a.iat[y+1,0],a.iat[y+2,0],a.iat[y+3,0],a.iat[y+4,0],a.iat[y+5,0]]))
            ig_post=ig_post.append(zz)
    except:
        print(" ")
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14

15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31

32
33
34
35
36
37
38

39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58

59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89

90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121

122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187

In [7]:
ig_post.insert(0, 'ig_post', range(1,len(ig_post)+1))
ig_post.columns =['Postid','Userid','Time','Caption','Likes','Comments','Comment']
ig_post.index = range(0,len(ig_post))
ig_post['Time']= ig_post['Time'].astype('str')

ig_post

,Postid,Userid,Time,Caption,Likes,Comments,Comment
0,1,300139600,2019-04-24 07:16:26,None,1102,14,🔥🔥
1,2,8174195,2019-04-24 06:12:26,#farouqisonfire🔥🔥🔥 #str8up #riprip,11691,142,Gang gang.
2,3,365278709,2019-04-24 08:44:09,🏀🏁,2658,56,You’re a beast 🍀
3,4,246667855,2019-04-24 22:55:32,Introducing Bloom Boheme Boozer!!!! At 37 Year...,24130,523,Awe sweet baby!! Congrats👑❤️
4,5,246667855,2019-04-24 16:59:47,"Come And Join Me In My Hometown Of Juneau, Ala...",14838,56,@handsome_rhdrob253 flw me
5,6,259244842,2019-04-24 03:29:49,Magical series. Let’s keep it going! #WeTheNorth,17631,198,Damn I miss that playoff atmosphere and what i...
6,7,1694451619,2019-04-24 16:48:15,#THANKYOU 🙏🏿,6161,264,@chris_turso @michael_iarrapino ❤️❤️
7,8,19547914,2019-04-24 15:24:10,Had a great family vacation to Paris.. and @ka...,2054,99,Congrats D!!
8,9,46714935,2019-04-24 17:04:06,"See you soon, 2nd round!",2882,50,Playa 👑👑👑
9,10,46714935,2019-04-24 06:05:01,My guy called it LONG before anyone ever knew....,30449,414,RIP freaking City!
10,11,297500919,2019-04-24 03:03:41,#Repost @bsnpr with @get_repost\n・・・\n😤😳 CLAVE...,6391,83,La emoción en esa cancha a otro nivel desp de ...
11,12,49910201,2019-04-24 05:32:05,I think we as a culture should all go buy a pa...,8513,156,@radsybowe they probably all went up 25%
12,13,4229905370,2019-04-25 01:09:05,Kawhi was dominant in the season series vs Phi...,1122,15,MAKE➕💲5000 ➕OVERNIGHT ➕NO MONEY➕NEEDED UPFRONT...
13,14,4229905370,2019-04-24 20:28:34,Ben is about to reunite with his daddy,2197,39,Total?
14,15,194908318,2019-04-25 00:27:00,Good Headspace. 🧘🏻‍♂️🧘🏻‍♂️🧘🏻‍♂️,41769,274,That’s what it’s all about bro find your peace
15,16,602470996,2019-04-24 19:40:55,Clear blue .... #vacation,3151,42,Ja też chcę El 👑
16,17,21005865,2019-04-24 03:53:46,Round 2,21172,207,let’s get it Mook.
17,18,199888020,2019-04-24 17:43:30,Nothing in the World like it!,34756,399,Wowww!!!... You have some hecka strong genes 💕
18,19,466834153,2019-04-24 22:50:48,Not happy about it look at that mean mug 😂😂😂,4278,65,haha he’s so cute 🖤
19,20,23489943,2019-04-24 18:34:32,The inside story of Kawhi's model face next to...,13652,288,@flave3 i’m gonna watch this one
20,21,211849705,2019-04-24 02:58:10,👏🏾 Miss you more......,6119,43,"rest up for next season man, big things coming💯"
21,22,8715481,2019-04-24 15:40:05,Your greatness is not what you have. It’s what...,13470,113,you're amazing @tobiasharris
22,23,8715481,2019-04-24 03:36:16,#NextUp 🙏🏽🙏🏽,36222,322,🔥🔥🔥
23,24,11773708,2019-04-24 21:30:02,Coldest sports photo ever. The Mona Lisa of sp...,3053,30,🎯🎯🎯💯💯💯

In [8]:
ig_post.to_csv('ig_post.csv',index=False)

In [9]:


ig_n = pd.read_csv("player_ig2.csv")
L = Instaloader()
ig_profile=pd.DataFrame()


for x in range(len(ig_n)):
    try:
        profile = Profile.from_username(L.context, ig_n.iat[x,2])
        tt = pd.DataFrame(np.column_stack([ig_n.iat[x,0],
                                           profile.full_name,profile.username, profile.userid,
                                           profile.biography,profile.external_url,profile.mediacount,
                                           profile.followers,profile.followees]))
        ig_profile=ig_profile.append(tt)

    except:
        print(" ")
    print(x)

ig_profile.columns = ['Player_id','Fullname','Username','Userid','Bio','Url','Posts','Followers','Following']
ig_profile.index = range(0,len(ig_profile))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14

15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187

In [10]:
ig_profile.to_csv('ig_profile.csv',index=False)

In [1]:
import enchant
d = enchant.Dict("en_US")
d.check("Hello")

True

In [2]:
d2 = enchant.DictWithPWL("en_US","misspell3.txt")

In [9]:
out= d2.suggest("teamprogressiondeily")

In [10]:
out

['progression',
 'retrogression',
 'progressively',
 'progressiveness',
 'teamprogressiondaily']

In [24]:
tags = pd.read_csv("misspell3.csv")
tags.head(5)

              risetogether
0             marchmadness
1  beststeakhousehandsdown
2                 historic
3                   str8up
4        detroitbasketball

In [6]:
d2.check("teamprogressiondaily")

True

In [3]:
import pandas as pd
tags = pd.read_csv("misspell3.csv")
tags.iat[1,0]

'beststeakhousehandsdown'

In [1]:
#mis-spelling table

import enchant
import pandas as pd
import numpy as np
d2 = enchant.DictWithPWL("en_US","misspell3.txt")

def mis(name):
    out= d2.suggest(name)
    if len(out) !=5:
        for x in range(len(out),5):
            out.insert(x, None)
    return out

tags = pd.read_csv("misspell3.csv")
mis_data=pd.DataFrame()

for x in range(0,len(tags),1):
    a=mis(tags.iat[x,0])
    #print (len(a))
   # for y in range(len(a)):
    zz=pd.DataFrame(np.column_stack([tags.iat[x,0],a[0],a[1],a[2],a[3],a[4]]))
    mis_data=mis_data.append(zz)

In [2]:
mis_data.columns =['Tags','Mis1','Mis2','Mis3','Mis4','Mis5']
mis_data.insert(0, 'id', range(1,len(mis_data)+1))
mis_data.index = range(0,len(mis_data))

In [4]:
mis_data.head(5)

,id,Tags,Mis1,Mis2,Mis3,Mis4,Mis5
0,1,marchmadness,march madness,marchioness,madness,manifoldness,marshiness
1,2,beststeakhousehandsdown,steakhouse,beststeakhousehandsdown,None,None,None
2,3,historic,historic,None,None,None,None
3,4,str8up,strumpet,Strauss,struck,strung,str8up
4,5,detroitbasketball,basketball,detroitbasketball,None,None,None

In [5]:
mis_data.to_csv('mis_data.csv',index=False)